config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:index, :new, :create]

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/blog.rb
# Make me Blog!!
class Blog
  def self.retrieve_articles
    Article.all
  end

  def self.create_article(params)
    Article.create(params)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Blog.retrieve_articles
  end

  def new
    @article = Article.new
  end

  def create
    Blog.create_article(article_params)
    redirect_to :articles
  end

  private

  def article_params
    params.require(:article).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.slim
.article

app/views/articles/index.html.slim
h1 Articles

= render @articles
#create_an_article= link_to 'New article', new_article_path

app/views/articles/new.html.slim
h1 Create a new article

= form_for @article do |f|
  = f.text_area :content
  = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pq</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>